#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config split_ratio         0.50
bspc config border_width        1
bspc config window_gap          5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate      true
bspc config auto_cancel         true
bspc config focused_border_color \#333333
bspc config normal_border_color  \#000000

bspc rule -a im desktop=9
bspc rule -a Ts3client_linux_amd64 desktop=9
bspc rule -a mpv floating
bspc rule -a Firefox desktop=2

wmname LG3D
