#!/bin/sh

set -e

# If there's an argument we only want to build that package.
only="$1"

rootdir="/var/pacman-j--root"

repodir="$(realpath repo)"
reponame="j--repo"

package() {
    pkg="$1"
    [ -n "$only" ] && [ "$only" != "$pkg" ] && return
    echo "++ Building package $pkg..."
    (
        cd "$pkg"
        rm -f *.pkg.tar.zst
        makechrootpkg -c -u -r "$rootdir" -D "$repodir"
    )
    pkgfile="$(basename $(ls $pkg/*.pkg.tar.zst))"
    cp "$pkg/$pkgfile" "$repodir/"
    repo-add "$repodir/$reponame.db.tar.zst" "$repodir/$pkgfile"
}

sudo mkdir -p "$rootdir"
mkdir -p "$repodir"

[ -d "$rootdir/root" ] || mkarchroot -C /etc/pacman.conf "$rootdir/root" base-devel

# AUR packages
package tamsyn-font
package lh2ctrl-git
package rebar3
package elixir-ls
package ttfautohint
package polymc
package cantata
package mise
package web-ext

# Personal packages
package j--slock
package j--ttf-input
package j--vr-video-player
package j--transcoding-music-server
package j--notification-listener
package j--ttf-iosevka-output

# Meta packages
package j--meta-base
package j--meta-tools
package j--meta-audio
package j--meta-graphical
package j--meta-wireless
package j--meta-gaming
package j--meta-dev
