[buildPlans.IosevkaOutput]
family = "Iosevka Output"
spacing = "term"
serifs = "sans"
noLigation = true

  [buildPlans.IosevkaOutput.variants]
  inherits = "ss18"

    [buildPlans.IosevkaOutput.variants.design]
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "single-storey-earless-corner"
    i = "tailed-serifed"
    l = "tailed-serifed"
    q = "straight-serifless"
    t = "flat-hook"
    lower-alpha = "crossing"
    zero = "slashed"
    four = "semi-open-serifless"
    seven = "bend-serifed"
    eight = "crossing-asymmetric"
    asterisk = "hex-low"
    brace = "curly-flat-boundary"
    number-sign = "upright"

  [buildPlans.IosevkaOutput.metricOverride]
  leading = 1130
  parenSize = 850
